### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mzanella** [snate/multipong#40]
- [ ] User satisfaction questions
- [x] Explain decisions about measurements ("latency", battery)
- [x] Problems Wi-Fi direct (in particular how to manage GO dead)
